name = "Java domain"
description = "Dynamic folder structure"
kickstart_version = 1

[[variables]]
name = "package"
default = "my.domain.test"
prompt = "Enter your package name (dot-separated):"
validation = "^[a-z]+(\\.[a-z][a-z0-9_]*)*$"

[[variables]]
name = "package_path"
default = "{{ package | replace(from='.', to='/')}}"
prompt = "Will not be asked since this is a derived variable"
derived = true
