name: ci
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [msrv, stable, macos, win-msvc]
        include:
          - build: msrv
            os: ubuntu-latest
            rust: 1.74.0
          - build: stable
            os: ubuntu-latest
            rust: stable
          - build: macos
            os: macOS-latest
            rust: stable
          - build: win-msvc
            os: windows-2019
            rust: stable
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Build System Info
        run: rustc --version
      - name: run tests
        run: cargo test
      - name: run all examples
        run: |
          cargo run -- examples/hooks/ --no-input
          cargo run -- examples/complex/ --no-input
          cargo run -- examples/default-from-variable/ --no-input
          cargo run -- examples/slugify/ --no-input
          cargo run -- examples/super-basic/ --no-input
          cargo run -- examples/with-directory/ --no-input